apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  postgres.conf: |-
    {{- .Values.config | nindent 4 }}
