apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-env
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{- if and (not (eq $key "POSTGRES_USER")) (not (eq $key "POSTGRES_PASSWORD")) }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
